name: Docs CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref || github.sha }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - uses: pnpm/action-setup@v6
        with:
          cache: true
      - name: LIB / Install packages
        run: pnpm install
      - name: LIB / Build
        run: pnpm build
      - name: DOCS / Install packages
        working-directory: docs
        run: pnpm install
      - name: DOCS / Build
        working-directory: docs
        run: pnpm build
